#!/bin/bash

export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_LOG_DIR=/var/log/apache2

# these should be set by the caller but in case they are not
export HTTPD_SERVER_ADMIN=${HTTPD_SERVER_ADMIN-root@localhost}
export HTTPD_SERVER_NAME=${HTTPD_SERVER_NAME-localhost}
export HTTPD_PROXY_PROTOCOL=${HTTPD_PROXY_PROTOCOL-Off}

mkdir -p /var/run/apache2
exec /usr/sbin/apache2 -DFOREGROUND
